In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("WSteamsbyDEF.csv")

### A Look at World Series Teams Defensive Ratings 2000-2019

In [5]:
df.head()

,Team,YEAR,WARrank,W,L,Postseason,WorldSeries,G,PA,HR,...,AVG,OBP,SLG,wOBA,wRC,EV,BsR,Off,Def,WAR
0,Phillies,2008,3,92,70,Y,Y,2396,6273,214,...,0.255,0.332,0.438,0.334,98,NaN,23.6,4.7,123.4,32.8
1,Cubs,2016,1,103,58,Y,Y,2332,6335,199,...,0.256,0.343,0.429,0.333,106,88.1,17.3,61.3,104.8,37.1
2,Giants,2010,6,92,70,Y,Y,2354,6143,162,...,0.257,0.321,0.408,0.320,98,NaN,-18.3,-31.6,95.2,25.8
3,Dodgers,2017,2,104,58,Y,Y,2464,6191,221,...,0.249,0.334,0.437,0.330,104,88.2,5.8,40.7,90.2,33.3
4,Diamondbacks,2001,6,92,70,Y,Y,2180,6349,208,...,0.267,0.341,0.442,0.336,97,NaN,-2.6,-31.4,88.6,26.0